name: Java CI with Gradle

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Устанавливаем JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      # 3. Делаем Gradle-обёртку исполняемой
      - name: Prepare Gradle wrapper
        run: chmod +x gradlew

      # 4. (Опционально) Сборка без тестов
      - name: Build without tests
        run: ./gradlew clean build -x test

      # 5. Запускаем тесты с генерацией отчёта JaCoCo
      - name: Run tests with JaCoCo
        run: ./gradlew test jacocoTestReport

      # 6. Загружаем HTML-отчёт JaCoCo как артефакт
      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report-${{ github.run_id }}
          path: build/reports/jacoco/test/html
          retention-days: 7

      # 7. Финальная полная сборка (если требуется)
      - name: Clean and full build
        run: ./gradlew clean build